# Generated by Django 3.1 on 2020-09-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20200919_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='author',
            name='connect',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='posts.Category'),
        ),
    ]
